import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import LogoutButton from "../components/logoutButton";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <nav className="bg-gray-800 p-4 text-white shadow-md">
            <div className="container mx-auto flex justify-between items-center">
              <div className="flex items-center gap-4">
                {/* <img src="/logo.png" alt="Logo" className="h-8" /> */}
                <Link href="/browse/events" className="text-2xl font-bold">Student Ticket Marketplace</Link>
              </div>
              <div className="flex items-center gap-6">
                <Link href="/list-ticket" className="px-3 py-2 rounded bg-blue-700 hover:bg-blue-600 transition-colors">
                  Sell
                </Link>
                <Link href="/browse/events" className="px-3 py-2 rounded bg-blue-700 hover:bg-blue-600 transition-colors">
                  Buy
                </Link>
                <Link href="/login" className="px-3 py-2 rounded bg-blue-700 hover:bg-blue-600 transition-colors">
                  Login
                </Link>
                <div className="relative group">
                  <button className="px-3 py-2 rounded bg-blue-700 hover:bg-blue-600 transition-colors">
                    Account
                  </button>
                  <div className="absolute right-0 mt-2 w-48 bg-white text-black rounded shadow-lg opacity-0 group-hover:opacity-100 transition-opacity">
                    <Link href="/account/profile" className="block px-4 py-2 hover:bg-gray-200">
                      Profile
                    </Link>
                    <Link href="/account/my-tickets" className="block px-4 py-2 hover:bg-gray-200">
                      My Tickets
                    </Link>
                    <Link href="/account/settings" className="block px-4 py-2 hover:bg-gray-200">
                      Settings
                    </Link>
                    <LogoutButton />
                  </div>
                </div>
              </div>
            </div>
          </nav>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
